version: "3.4"

volumes:
  mongo_data:
    name: appy_mongo_data

networks:
  backend:

services:

  mongo:
    image: mongo:3.6.4
    ports:
      - 27017:27017
    volumes:
      - "mongo_data:/data/db"
    networks:
      - backend
    restart: always

  api:
    build: ./
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      # Share the entire project except "node_modules". This prevents us from having to COPY the project files
      #   in the Dockerfile, while still keeping separate node dependency files.
      - "./:/backend"
      - "/backend/node_modules"
    networks:
      - backend
    depends_on:
      - mongo
    env_file:
      - ./.env-docker
